name:                coq-aern-extracted
version:             0.1.0.0
github:              "holgerthies/coq-aern"
license:             MIT
author:              "Michal Konečný, Holger Thies, Sewon Park"
maintainer:          "mikkonecny@gmail.com"
copyright:           "2021 Michal Konečný, Holger Thies, Sewon Park"

# extra-source-files:
# - README.md

# Metadata used when publishing your package
synopsis:            Exact real programs extracted from coq-aern
category:            Math

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/holgerthies/coq-aern>

dependencies:
- base == 4.*
- integer-logarithms
- collect-errors >= 0.1.3
- mixed-types-num >= 0.5.1
- aern2-mp >= 0.2
- aern2-real >= 0.2

library:
  source-dirs: src
  ghc-options:
  - -Wall -fno-warn-missing-signatures -fno-warn-partial-type-signatures -fno-warn-unused-imports -fno-warn-name-shadowing

executables:
  coq-aern-extracted-bench:
    main:                bench.hs
    source-dirs:         bench
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    - -Wall
    - -O2
    dependencies:
    - aern2-mp
    - aern2-real
    - coq-aern-extracted
    - criterion
    - deepseq

# benchmarks:
#   coq-aern-extracted-bench:
#     main:                bench.hs
#     source-dirs:         bench
#     ghc-options:
#     - -rtsopts
#     - -threaded
#     - -with-rtsopts=-N
#     - -Wall
#     - -O2
#     dependencies:
#     - aern2-mp
#     - aern2-real
#     - coq-aern-extracted
#     - containers
#     - deepseq
#     - criterion
#     - parallel
