Require Export Real.RealAssumption.
Require Export Base.ClassicalMonads Classical.Partiality Classical.PartialReals Classical.Continuity Classical.ContinuousPartialRealFunctions Classical.Topology Classical.Differentiability.
